#!/usr/bin/env sh
FERRUM_EXISTS="$(gem list -i ferrum -v 0.12)"

if [[ $FERRUM_EXISTS == "false" ]]; then
    echo "
* INFO - ferrum not found
  It doesn't look like the ferrum gem is installed. Lemme install that for you.
"
    gem install ferrum -v 0.12
fi

# if windows then run irb --inf-ruby-mode -r
if [[ "$OSTYPE" == "msys" || "$OSTYPE" == "cygwin" ]]; then
    irb --inf-ruby-mode -r ./buddy-repl.rb
else
    irb -r ./buddy-repl.rb
fi
